# language: php
 
# php:
#   - 5.4
#   - 5.5
#   - 5.6
#	- 5.1
#   - hhvm

# before_script:
#   - composer self-update
#   - composer install --prefer-source --no-interaction --dev

# script: phpunit -c vendor/bin/tes.php

# matrix:
#   allow_failures:
#     - php: 5.1
#     - php: hhvm
#   fast_finish: true

# notifications:
#   on_success: always
#   on_failure: always

language: php

php: 5.1

script: phpunit vendor/bin/tes.php

matrix:
  allow_failures:
    php: 5.1
  fast_finish: true